#!/bin/sh

case "$1" in
    start)
        echo "Loading aesd-char-driver module..."
        aesdchar_load
        ;;
    stop)
        echo "Unloading aesd-char-driver module..."
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
